import { CATEGORY_COLLECTION } from "./Category";
import { DOCUMENT_TYPE_COLLECTION } from "./DocumentType";
import { GENDER_COLLECTION } from "./Gender";
import { MODULE_COLLECTION } from "./Module";
import { ORDER_COLLECTION, ORDER_DETAILS_COLLECTION } from "./Order";
import { PRODUCT_COLLECTION } from "./Product";
import { RECEPTION_COLLECTION } from "./Reception";
import { ROLE_COLLECTION, ROLE_ACCESS_COLLECTION } from "./Role";
import { SETTING_COLLECTION } from "./Setting";
import { SYSTEM_USER_COLLECTION } from "./SystemUser";
import { USER_COLLECTION } from "./User";

export {
  SETTING_COLLECTION,
  MODULE_COLLECTION,
  ROLE_COLLECTION,
  ROLE_ACCESS_COLLECTION,
  SYSTEM_USER_COLLECTION,
  CATEGORY_COLLECTION,
  PRODUCT_COLLECTION,
  GENDER_COLLECTION,
  DOCUMENT_TYPE_COLLECTION,
  USER_COLLECTION,
  RECEPTION_COLLECTION,
  ORDER_COLLECTION,
  ORDER_DETAILS_COLLECTION,
};
